[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#ff3045"
backgroundColor = "#090b10"
secondaryBackgroundColor = "#1f1f28"
textColor = "#f8fafc"
